# Álgebra matricial

# Valores y vectores Propios

Se dice que un vector $v$ es un $vector \; propio$ de la matriz $A$ si este satisface la siguiente ecuación


\begin{equation}
A v = \lambda v
\end{equation}


donde $\lambda$ es un escalar llamado valor propio asociado al vector propio $v$.

# Matriz diagonalizable


Una  matriz $A$ cuadrada esdiagonalizable si existen  dos  matrices cuadradas $Q$ y $\Delta$ tales que $Q$ es invertible y $\Delta$ es diagonal y 

$$
A = Q \Lambda Q^{-1}
$$

donde $Q$ es la matriz formado por los autovectores y $\Lambda$ es la matriz diagonal que contiene los autovalores.

In [3]:
from numpy import array
from numpy.linalg import eig

In [4]:
#definimos la matriz
A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

In [5]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# se calculan los autovectores y los autovalores 
valores, vectores = eig(A)

In [10]:
print(valores)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [11]:
print(vectores)

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


# Confirmación de los autovectores

In [ ]:
Las dos multiplicaciones de la definición tienen que dar el mismo resultado

In [15]:
B = A.dot(vectores[: , 0])
print(B)

[ -3.73863537  -8.46653421 -13.19443305]


In [17]:
valores[0]*vectores[: , 0]

array([ -3.73863537,  -8.46653421, -13.19443305])

Como se observa, se cumple la igualdad!!

# Reconstrucción de la matriz 

In [18]:
from numpy import diag
from numpy.linalg import inv

In [54]:
Q = vectores
R = inv(Q)
L = diag(valores)
B = Q.dot(L).dot(R)

In [55]:
B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

# Ejercicio de seguimiento

Calcular los valores propios y los vectores propios de la matriz

$$A = 
\begin{bmatrix}
4 & -3 \\
2 & -1
\end{bmatrix}
$$

# solución:

Primero

Los valores propios son las raices del polinomio característico que es el determinante de la matriz $( A - \lambda I )$.
Entonces

$$
\det(A-\lambda I) \;=\; (4-\lambda)(-1-\lambda) + 6 \;=\; -4 - 3 \lambda + \lambda^2 +6 \;=\; (\lambda - 1) (\lambda - 2) =0 
$$

Por tanto los autovalores son $\lambda = 1$ y $\lambda = 2$

Segundo encontramos los autovectores asociados a cada valor propio:

Vector propio asociado a $\lambda = 1$:

La ecuación que se tiene que resolver es $A v = \lambda v$ sustituyendo los valores de la matriz y el valor de $\lambda = 1$ 

$$
\begin{bmatrix}
4 & -3 \\
2 & -1
\end{bmatrix}
\begin{bmatrix}
v_1 \\
v_2 
\end{bmatrix}
=
\begin{bmatrix}
v_1 \\
v_2 
\end{bmatrix}
$$

$$
\begin{bmatrix}
4v_1 - 3v_2 \\
2v_1 - 1v_2
\end{bmatrix}
=
\begin{bmatrix}
v_1 \\
v_2 
\end{bmatrix}
$$

$$
\begin{bmatrix}
3v_1 - 3v_2 \\
2v_1 - 2v_2
\end{bmatrix}
=
\begin{bmatrix}
0 \\
0 
\end{bmatrix}
$$

La solución es obviamente $v_1 = v_2$, que se expresa como $(v_1, v_2)=v_1(1, 1)$

#### se hace el mismo procedimiento para el segundo valor propio $\lambda = 2$

$$
\begin{bmatrix}
4 & -3 \\
2 & -1
\end{bmatrix}
\begin{bmatrix}
v_1 \\
v_2 
\end{bmatrix}
=
2
\begin{bmatrix}
v_1 \\
v_2 
\end{bmatrix}
$$

$$
\begin{bmatrix}
4v_1 - 3v_2 \\
2v_1 - 1v_2
\end{bmatrix}
=
2
\begin{bmatrix}
v_1 \\
v_2 
\end{bmatrix}
$$

$$
\begin{bmatrix}
2v_1 - 3v_2 \\
2v_1 - 3v_2
\end{bmatrix}
=
\begin{bmatrix}
0 \\
0 
\end{bmatrix}
$$

La solución es la recta $v_2 = \frac{2}{3} v_1$, que se expresa como $(v_1, v_2) = (v_1, \frac{2}{3} v_1)=v_1(1,\frac{2}{3} )$

### Usando python

In [65]:
# ahora usando python sale en una línea
AA = array([[4, -3], [2, -1]])
valoress, vectoress = eig(AA)
print('valores propios')
print(valoress)
print(' ')
print("vectores propios")
print(vectoress)

valores propios
[2. 1.]
 
vectores propios
[[0.83205029 0.70710678]
 [0.5547002  0.70710678]]


más ejercicios se encuentran en esta página

https://www.studocu.com/en/document/universidad-de-sevilla/algebra-lineal/practical/practico-ejercicios-resueltos-autovalores-y-autovectores/339913/view
    