# Manejo de matrices con python 

Uso del paquete numpy

In [1]:
import numpy as np

In [2]:
data1 = [1, 2, 3, 4, 5]     # con esta isntrucción se define una lista

v     = np.array(data1)     # se convierte la lista en un array de una dimension


### Arrays especiales

In [6]:
np.ones(10)       #vetor de unos de longitud 10
np.zeros(10)      #vetor de ceros de longitud 10 
np.zeros((3,6))   #matriz de ceros 3 filas y 6 columnas  

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.linspace(-1, 1, 5) # De -1 a 1 (inclusive) con 5 puntos 


array([-1. , -0.5,  0. ,  0.5,  1. ])

#### Dimensiones 

In [23]:
M = np.ones((4,6))
M

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [25]:
M.shape    # devuelve el tamanao de la matriz. 

(4, 6)

In [27]:
M.ndim     # array de dos dimensiones

2

In [28]:
M.size     # el numero total de elementos  

24

In [29]:
len(M)     # Tamanano de la primera dimension 

4

#### Transpuesta 

In [31]:
M.T

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### agregar filas 

In [39]:
a = np.array([0,11])
b = np.array([20,33])

ab = np.vstack((a,b))
ab

array([[ 0, 11],
       [20, 33]])

#### seleccion de elementos de la matriz

In [48]:
A = np.arange(100, dtype=float).reshape((10,10))
A

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [49]:
A[0]           #selecciona la primera fila

A[0][3]        #fila 0, columna 3 Devuelve el 3

3.0

En general para seleccionar partes de la matriz se usa la sintaxis: 

                             [inicio_fila : fin_fila   ,  inicio_columna : fin_columna]    

In [53]:
A[3:6, 2:6]    #de la fila 3 a la fila 5       Y       de la columna 2 a la columna 5 

array([[32., 33., 34., 35.],
       [42., 43., 44., 45.],
       [52., 53., 54., 55.]])

voy en la pagina 81 del libro

# Norma y distancia

La norma 2 de un vector $a\in R^n$ se denota por 

$$
||a||_2 = \sqrt{\sum_i^n a_i^2}
$$

La distancia entre los dos vectores $a$ y $b$ se calcula entonces de la siguiente manera

$$
||a-b||_2 = \sqrt{\sum_i^n (a_i-b_i)^2}
$$

Adicionalmente la norma uno se define como 

$$
||a||_1 = {\sum_i^n |a_i|}
$$

#### El producto interno del vector $a$ con el vector $b$ es 

$$
a \cdot b = \sum_i^n a_i\;b_i 
$$

In [61]:
a = np.array([2, 4, 6])
b = np.array([-3, 0, 11])

#El producto interno de acon b :

a.dot(b)

60

In [66]:
#### la norma uno de a
from numpy.linalg import norm
a

array([2, 4, 6])

In [64]:
norma_1_de_a = norm(a,1)
norma_1_de_a

12.0

In [67]:
#### la norma 2 de b
b

array([-3,  0, 11])

In [68]:
norma_2_de_b = norm(b,2)
norma_2_de_b

11.40175425099138

#### la funcion " dot " también sirve para multiplicar matrices

Por ejemplo multipliquemos una matriz con su inversa para comprobar que se obtiene la matriz identidad

In [93]:
from numpy.linalg import inv, det
from numpy import identity, trace

In [90]:
A = [[2, 4, 5, 6, 1],
     [1, 8, 7, 9 ,1],
    [-2, 0, 1, 9, 11],
    [ 3, 5, 7, 8, 0],
    [ 1, 7, 2, 9, 1]]
AA = np.array(A) 
AA

array([[ 2,  4,  5,  6,  1],
       [ 1,  8,  7,  9,  1],
       [-2,  0,  1,  9, 11],
       [ 3,  5,  7,  8,  0],
       [ 1,  7,  2,  9,  1]])

In [91]:
AA.dot(inv(AA)).round(2)

array([[ 1., -0., -0., -0.,  0.],
       [ 0.,  1.,  0., -0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0., -0.,  0.,  1.,  0.],
       [-0., -0.,  0., -0.,  1.]])

In [92]:
identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [96]:
# determinante de AA
determinante = det(AA)
print ('El determinante es ',determinante)

# traza de AA 
traza = trace(AA)
print ('La traza es ',traza)

El determinante es  877.9999999999994
La traza es  20
